before_script:
  - sudo apt-get -y install build-essential cmake pkg-config libboost-serialization-dev libboost-program-options-dev libboost-filesystem-dev libboost-graph-dev libopencv-dev qtbase5-dev qtbase5-dev-tools libglibmm-2.4-dev

stages:
  - prepare
  - build
  - test


# download uipf
build-uipf:
  stage: prepare
  script:
    - . <(curl -fsSL https://gitlab.cebe.cc/global/gitlab-ci-helpers/raw/master/get-last-successful-build-artifact.sh)
    - PROJECT=master/uipf PRIVATE_TOKEN=privtoken STAGE=build-uipf-with-cv download_latest
  artifacts:
    paths:
    - prefix/


build-uipf-sfm:
  stage: build
  script:
    - if [ -d build/ ]; then rm -rf build/ ; fi
    - mkdir build/ && cd build/
    - cmake -DCMAKE_INSTALL_PREFIX=`pwd`/prefix ..
    - make -j 4
  dependencies:
  - build-uipf

test:
  stage: test
  script:
    - ./prefix/bin/uipf -l
    # TODO grep for expected modules
  dependencies:
  - build-uipf-sfm


variables:
  GIT_STRATEGY: clone
