usr/lib/libuipf-sfm.so
usr/lib/libuipf-sfm.so.1.0
usr/lib/libuipf-sfm.so.1.0.0
usr/lib/libuipf-sfm-libply.so
usr/lib/libuipf-sfm-libply.so.0
usr/lib/libuipf-sfm-libply.so.0.1

usr/lib/uipf/libSfMImage2OpenCVMatModule.so
usr/lib/uipf/libSfMOpenCVMat2ImageModule.so
usr/lib/uipf/libSfMLoadImageModule.so
usr/lib/uipf/libSfMLoadImagesModule.so
usr/lib/uipf/libSfMCopyImage.so
usr/lib/uipf/libSfMLoadPointCloud.so